DEFAULT_ACTIVE_SCANNER = None
DEFAULT_SCAN_MODE = "Color"
DEFAULT_SCAN_RESOLUTION = 75

DEFAULT_THUMBNAIL_SIZE = 128

STATUSBAR_BASE_CONTEXT_ID = 0
STATUSBAR_PREVIEW_CONTEXT_ID = 1
STATUSBAR_SCAN_CONTEXT_ID = 2